/* Main.ino file generated by New Project wizard
 *
 * Created:   Tue Aug 18 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

void setup(){
    pinMode(8, OUTPUT);
    pinMode(9, OUTPUT);
}

void loop(){
    digitalWrite(8,LOW);
    delay(5);
    digitalWrite(8,HIGH);
    delay(1);
    digitalWrite(8,LOW);
    delay(4);
    digitalWrite(9,LOW);
    delay(5);
    digitalWrite(9,HIGH);
    delay(1);
    digitalWrite(9,LOW);
    delay(4);
}
