/* Main.ino file generated by New Project wizard
 *
 * Created:   Mon Aug 24 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

void setup(){
    pinMode(8,OUTPUT);
    pinMode(9,OUTPUT);
    pinMode(10,INPUT);
}

void loop(){
    if(digitalRead(10)==HIGH){
        digitalWrite(8,LOW);
        delay(5);
        digitalWrite(8,HIGH);
        delay(1);
        digitalWrite(8,LOW);
        delay(4);
        digitalWrite(9,LOW);
        delay(5);
        digitalWrite(9,HIGH);
        delay(2);
        digitalWrite(9,LOW);
        delay(1);
    }
    else{
        digitalWrite(8,LOW);
        digitalWrite(9,LOW);
    }
}
